# 服务器端口配置
server:
  port: 8080
  servlet:
    context-path: /api
# Spring 配置
spring:
  application:
    name: MyBlog
  profiles:
    active: dev
  # 数据源配置
  datasource:
    driver-class-name: ${spring.datasource.driver-class-name}
    url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
# MyBatis 配置
mybatis:
  # Mapper XML 文件配置
  mapper-locations: classpath:mapper/*.xml
  # 实体类包路径
  type-aliases-package: com.blog.entity
  # 开启驼峰命名自动映射
  configuration:
    map-underscore-to-camel-case: true
# 日志配置
logging:
  level:
    com:
      blog:
        mapper: debug
        controller: info
        service: info
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    # 自定义swagger前端请求路径,例：输入http:localhost:8080/swagger-ui.html会自动重定向到swagger页面
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    # swagger后端请求地址
    path: /v3/api-docs
  # 分组配置
  group-configs:
    # 分组名称
    - group: 'userAPI'
      paths-to-match: '/user/**'
      packages-to-scan: com.blog.controller
    - group: 'adminAPI'
      paths-to-match: '/admin/**'
      packages-to-scan: com.blog.controller
# knife4j的增强配置，不需要可以不配
knife4j:
  # 开启knife4j,无需添加@EnableKnife4j注解
  enable: true
  setting:
    language: zh_cn
blog:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    secret-key: abcdefghijklmnopqrstuvwxyz1234567891
    # 设置jwt过期时间 2小时
    ttl: 7200000
    # 设置前端传递过来的令牌名称
    token-name: authentication